### ISSUE TITLE
job broken?!

### ISSUE THREAD

**Issue by goern** [thoth-station/graph-sync-job#26] opened 2018-07-03 19:50 UTC
```

---> Running application from Python script (app.py) ...
--
  | INFO:thoth:Setting up logging to rsyslog endpoint 10.0.18.51:30514
  | --- Logging error ---
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 352, in emit
  | self.socket.sendto(syslog_msg, self.address)
  | TypeError: an integer is required (got type str)
  | Call stack:
  | File "app.py", line 112, in <module>
  | _LOGGER.info(f"graph-sync-job v{__version__} starting...")
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1306, in info
  | self._log(INFO, msg, args, **kwargs)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
  | self.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
  | self.callHandlers(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
  | hdlr.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
  | self.emit(record)
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 356, in emit
  | self.handleError(record)
  | Message: 'graph-sync-job v0.3.0+thoth_storage.0.0.29 starting...'
  | Arguments: ()
  | INFO:thoth.graph_sync_job:graph-sync-job v0.3.0+thoth_storage.0.0.29 starting...
  | --- Logging error ---
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 352, in emit
  | self.socket.sendto(syslog_msg, self.address)
  | TypeError: an integer is required (got type str)
  | Call stack:
  | File "app.py", line 114, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 697, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 80, in cli
  | f"Syncing solver results from {solver_results_store_host} to {graph_hosts}")
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1306, in info
  | self._log(INFO, msg, args, **kwargs)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
  | self.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
  | self.callHandlers(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
  | hdlr.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
  | self.emit(record)
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 356, in emit
  | self.handleError(record)
  | Message: "Syncing solver results from None to ('janusgraph',)"
  | Arguments: ()
  | INFO:thoth.graph_sync_job:Syncing solver results from None to ('janusgraph',)
  | --- Logging error ---
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 352, in emit
  | self.socket.sendto(syslog_msg, self.address)
  | TypeError: an integer is required (got type str)
  | Call stack:
  | File "app.py", line 114, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 697, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 84, in cli
  | f"Syncing solver document with id {document_id!r} to graph")
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1306, in info
  | self._log(INFO, msg, args, **kwargs)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
  | self.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
  | self.callHandlers(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
  | hdlr.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
  | self.emit(record)
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 356, in emit
  | self.handleError(record)
  | Message: "Syncing solver document with id 'fridex-thoth-solver-fc26-thoth-solver-fc26-98rx4' to graph"
  | Arguments: ()
  | INFO:thoth.graph_sync_job:Syncing solver document with id 'fridex-thoth-solver-fc26-thoth-solver-fc26-98rx4' to graph
  | --- Logging error ---
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 352, in emit
  | self.socket.sendto(syslog_msg, self.address)
  | TypeError: an integer is required (got type str)
  | Call stack:
  | File "app.py", line 114, in <module>
  | cli()
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 697, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  | return callback(*args, **kwargs)
  | File "app.py", line 84, in cli
  | f"Syncing solver document with id {document_id!r} to graph")
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1306, in info
  | self._log(INFO, msg, args, **kwargs)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
  | self.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
  | self.callHandlers(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
  | hdlr.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
  | self.emit(record)
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 356, in emit
  | self.handleError(record)
  | Message: "Syncing solver document with id 'fridex-thoth-solver-fc26-thoth-solver-fc26-tsb4s' to graph"
  | Arguments: ()
  | INFO:thoth.graph_sync_job:Syncing solver document with id 'fridex-thoth-solver-fc26-thoth-solver-fc26-tsb4s' to graph

```

**Comment by ace2107** [comment] 2018-07-16 19:06
We no longer have this issue,right ? Which is why i closed it.

**Comment by fridex** [comment] 2018-07-17 07:10
> We no longer have this issue,right ? Which is why i closed it.

The issue is reported by the logging system - rfc5424logging handler cannot expand arguments that is somehow broken design as it makes the handler unusable. We will need to replace it.

Pushing logs is now turned off, we will need to change it anyway based on the ongoing discussion. I would close this issue as we will need to rewrite this logic anyway.

**Closed by fridex** 2018-07-17 07:10 UTC
Labels: bug
